# Generated by Django 5.0.6 on 2024-06-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_links', '0002_alter_sociallinks_options_alter_sociallinks_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SocialLinks',
        ),
    ]
