from django.contrib import admin
from .models import Category,Blog


#pre populate slug
class BlogAdmin(admin.ModelAdmin):
    
    # Pre populate slugs - autogenerated
    prepopulated_fields = {'slug':('title',)}
    
    #admin panel customization
    list_display = ('title','category','author','status','is_featured',)
    search_fields = ('id','title','category__category_name','status')
    list_editable = ('is_featured',)

# Register your models here.
admin.site.register(Category)
admin.site.register(Blog,BlogAdmin)
