# Generated by Django 5.0.6 on 2024-06-09 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
