# Generated by Django 5.0.6 on 2024-08-15 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_alter_blog_slug'),
        ('blog_app', '0008_comment'),
    ]

    operations = [
    ]
